categories:
  - title: '🐛 Fixes'
    label: 'Bugfix'
  - title: '✨ Features'
    label: 'Feature'
  - title: '🧭 Changes'
    label: 'Enhancement'
  - title: '📦 Dependency updates'
    labels:
      - 'Renovate'
      - 'Dependency updates'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&@'
exclude-contributors:
  - 'renovate'
template: |
  ## FastAsyncVoxelSniper v

  $CHANGES
