files:
  - source: '/src/main/resources/lang/strings.json'
    ignore:
      - '/src/main/resources/lang/%file_name%_%two_letters_code%.json'
    translation: '/src/main/resources/lang/%file_name%_%two_letters_code%.json'

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
