package com.thevoxelbox.voxelsniper;

import com.thevoxelbox.voxelsniper.brush.BrushTypeRegistry;
import com.thevoxelbox.voxelsniper.brush.type.BiomeBrush;
import com.thevoxelbox.voxelsniper.brush.type.BlockResetBrush;
import com.thevoxelbox.voxelsniper.brush.type.BlockResetSurfaceBrush;
import com.thevoxelbox.voxelsniper.brush.type.CleanSnowBrush;
import com.thevoxelbox.voxelsniper.brush.type.CometBrush;
import com.thevoxelbox.voxelsniper.brush.type.CopyPastaBrush;
import com.thevoxelbox.voxelsniper.brush.type.DomeBrush;
import com.thevoxelbox.voxelsniper.brush.type.DrainBrush;
import com.thevoxelbox.voxelsniper.brush.type.EntityBrush;
import com.thevoxelbox.voxelsniper.brush.type.EntityRemovalBrush;
import com.thevoxelbox.voxelsniper.brush.type.EraserBrush;
import com.thevoxelbox.voxelsniper.brush.type.ErodeBrush;
import com.thevoxelbox.voxelsniper.brush.type.ExtrudeBrush;
import com.thevoxelbox.voxelsniper.brush.type.FlatOceanBrush;
import com.thevoxelbox.voxelsniper.brush.type.GenerateTreeBrush;
import com.thevoxelbox.voxelsniper.brush.type.HeatRayBrush;
import com.thevoxelbox.voxelsniper.brush.type.JockeyBrush;
import com.thevoxelbox.voxelsniper.brush.type.LightningBrush;
import com.thevoxelbox.voxelsniper.brush.type.MoveBrush;
import com.thevoxelbox.voxelsniper.brush.type.OceanBrush;
import com.thevoxelbox.voxelsniper.brush.type.PaintingBrush;
import com.thevoxelbox.voxelsniper.brush.type.PullBrush;
import com.thevoxelbox.voxelsniper.brush.type.RandomErodeBrush;
import com.thevoxelbox.voxelsniper.brush.type.RegenerateChunkBrush;
import com.thevoxelbox.voxelsniper.brush.type.Rotation2DBrush;
import com.thevoxelbox.voxelsniper.brush.type.Rotation2DVerticalBrush;
import com.thevoxelbox.voxelsniper.brush.type.Rotation3DBrush;
import com.thevoxelbox.voxelsniper.brush.type.RulerBrush;
import com.thevoxelbox.voxelsniper.brush.type.ScannerBrush;
import com.thevoxelbox.voxelsniper.brush.type.SetRedstoneFlipBrush;
import com.thevoxelbox.voxelsniper.brush.type.ShellBallBrush;
import com.thevoxelbox.voxelsniper.brush.type.ShellSetBrush;
import com.thevoxelbox.voxelsniper.brush.type.ShellVoxelBrush;
import com.thevoxelbox.voxelsniper.brush.type.SignOverwriteBrush;
import com.thevoxelbox.voxelsniper.brush.type.SnowConeBrush;
import com.thevoxelbox.voxelsniper.brush.type.SpiralStaircaseBrush;
import com.thevoxelbox.voxelsniper.brush.type.StencilBrush;
import com.thevoxelbox.voxelsniper.brush.type.StencilListBrush;
import com.thevoxelbox.voxelsniper.brush.type.TreeSnipeBrush;
import com.thevoxelbox.voxelsniper.brush.type.VoltMeterBrush;
import com.thevoxelbox.voxelsniper.brush.type.WarpBrush;
import com.thevoxelbox.voxelsniper.brush.type.blend.BlendBallBrush;
import com.thevoxelbox.voxelsniper.brush.type.blend.BlendDiscBrush;
import com.thevoxelbox.voxelsniper.brush.type.blend.BlendVoxelBrush;
import com.thevoxelbox.voxelsniper.brush.type.blend.BlendVoxelDiscBrush;
import com.thevoxelbox.voxelsniper.brush.type.canyon.CanyonBrush;
import com.thevoxelbox.voxelsniper.brush.type.canyon.CanyonSelectionBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.BallBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.BlobBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.CheckerVoxelDiscBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.CylinderBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.DiscBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.DiscFaceBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.EllipseBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.EllipsoidBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.FillDownBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.JaggedLineBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.LineBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.OverlayBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.PunishBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.RingBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.SetBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.SnipeBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.SplatterBallBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.SplatterDiscBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.SplatterOverlayBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.SplatterVoxelBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.SplineBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.ThreePointCircleBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.TriangleBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.UnderlayBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.VoxelBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.VoxelDiscBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.VoxelDiscFaceBrush;
import com.thevoxelbox.voxelsniper.brush.type.stamp.CloneStampBrush;

public class BrushTypeRegistrar {

	private BrushTypeRegistry registry;

	public BrushTypeRegistrar(BrushTypeRegistry registry) {
		this.registry = registry;
	}

	public void registerBrushTypes() {
		this.registry.registerBrushType(BallBrush.class, "b", "ball");
		this.registry.registerBrushType(BiomeBrush.class, "bio", "biome");
		this.registry.registerBrushType(BlendBallBrush.class, "bb", "blendball");
		this.registry.registerBrushType(BlendDiscBrush.class, "bd", "blenddisc");
		this.registry.registerBrushType(BlendVoxelBrush.class, "bv", "blendvoxel");
		this.registry.registerBrushType(BlendVoxelDiscBrush.class, "bvd", "blendvoxeldisc");
		this.registry.registerBrushType(BlobBrush.class, "blob", "splatblob");
		this.registry.registerBrushType(BlockResetBrush.class, "brb", "blockresetbrush");
		this.registry.registerBrushType(BlockResetSurfaceBrush.class, "brbs", "blockresetbrushsurface");
		this.registry.registerBrushType(CanyonBrush.class, "ca", "canyon");
		this.registry.registerBrushType(CanyonSelectionBrush.class, "cas", "canyonselection");
		this.registry.registerBrushType(CheckerVoxelDiscBrush.class, "cvd", "checkervoxeldisc");
		this.registry.registerBrushType(CleanSnowBrush.class, "cls", "cleansnow");
		this.registry.registerBrushType(CloneStampBrush.class, "cs", "clonestamp");
		this.registry.registerBrushType(CometBrush.class, "com", "comet");
		this.registry.registerBrushType(CopyPastaBrush.class, "cp", "copypasta");
		this.registry.registerBrushType(CylinderBrush.class, "c", "cylinder");
		this.registry.registerBrushType(DiscBrush.class, "d", "disc");
		this.registry.registerBrushType(DiscFaceBrush.class, "df", "discface");
		this.registry.registerBrushType(DomeBrush.class, "dome", "domebrush");
		this.registry.registerBrushType(DrainBrush.class, "drain");
		this.registry.registerBrushType(EllipseBrush.class, "el", "ellipse");
		this.registry.registerBrushType(EllipsoidBrush.class, "elo", "ellipsoid");
		this.registry.registerBrushType(EntityBrush.class, "en", "entity");
		this.registry.registerBrushType(EntityRemovalBrush.class, "er", "entityremoval");
		this.registry.registerBrushType(EraserBrush.class, "erase", "eraser");
		this.registry.registerBrushType(ErodeBrush.class, "e", "erode");
		this.registry.registerBrushType(ExtrudeBrush.class, "ex", "extrude");
		this.registry.registerBrushType(FillDownBrush.class, "fd", "filldown");
		this.registry.registerBrushType(FlatOceanBrush.class, "fo", "flatocean");
		this.registry.registerBrushType(GenerateTreeBrush.class, "gt", "generatetree");
		this.registry.registerBrushType(HeatRayBrush.class, "hr", "heatray");
		this.registry.registerBrushType(JaggedLineBrush.class, "j", "jagged");
		this.registry.registerBrushType(JockeyBrush.class, "jockey");
		this.registry.registerBrushType(LightningBrush.class, "light", "lightning");
		this.registry.registerBrushType(LineBrush.class, "l", "line");
		this.registry.registerBrushType(MoveBrush.class, "mv", "move");
		this.registry.registerBrushType(OceanBrush.class, "o", "ocean");
		this.registry.registerBrushType(OverlayBrush.class, "over", "overlay");
		this.registry.registerBrushType(PaintingBrush.class, "paint", "painting");
		this.registry.registerBrushType(PullBrush.class, "pull");
		this.registry.registerBrushType(PunishBrush.class, "p", "punish");
		this.registry.registerBrushType(RandomErodeBrush.class, "re", "randomerode");
		this.registry.registerBrushType(RegenerateChunkBrush.class, "gc", "generatechunk");
		this.registry.registerBrushType(RingBrush.class, "ri", "ring");
		this.registry.registerBrushType(Rotation2DBrush.class, "rot2", "rotation2d");
		this.registry.registerBrushType(Rotation2DVerticalBrush.class, "rot2v", "rotation2dvertical");
		this.registry.registerBrushType(Rotation3DBrush.class, "rot3", "rotation3d");
		this.registry.registerBrushType(RulerBrush.class, "r", "ruler");
		this.registry.registerBrushType(ScannerBrush.class, "sc", "scanner");
		this.registry.registerBrushType(SetBrush.class, "set");
		this.registry.registerBrushType(SetRedstoneFlipBrush.class, "setrf", "setredstoneflip");
		this.registry.registerBrushType(ShellBallBrush.class, "shb", "shellball");
		this.registry.registerBrushType(ShellSetBrush.class, "shs", "shellset");
		this.registry.registerBrushType(ShellVoxelBrush.class, "shv", "shellvoxel");
		this.registry.registerBrushType(SignOverwriteBrush.class, "sio", "signoverwriter");
		this.registry.registerBrushType(SnipeBrush.class, "s", "snipe");
		this.registry.registerBrushType(SnowConeBrush.class, "snow", "snowcone");
		this.registry.registerBrushType(SpiralStaircaseBrush.class, "sstair", "spiralstaircase");
		this.registry.registerBrushType(SplatterBallBrush.class, "sb", "splatball");
		this.registry.registerBrushType(SplatterDiscBrush.class, "sd", "splatdisc");
		this.registry.registerBrushType(SplatterOverlayBrush.class, "sover", "splatteroverlay");
		this.registry.registerBrushType(SplatterVoxelBrush.class, "sv", "splattervoxel");
		this.registry.registerBrushType(SplatterDiscBrush.class, "svd", "splatvoxeldisc");
		this.registry.registerBrushType(SplineBrush.class, "sp", "spline");
		this.registry.registerBrushType(StencilBrush.class, "st", "stencil");
		this.registry.registerBrushType(StencilListBrush.class, "sl", "stencillist");
		this.registry.registerBrushType(ThreePointCircleBrush.class, "tpc", "threepointcircle");
		this.registry.registerBrushType(TreeSnipeBrush.class, "t", "tree", "treesnipe");
		this.registry.registerBrushType(TriangleBrush.class, "tri", "triangle");
		this.registry.registerBrushType(UnderlayBrush.class, "under", "underlay");
		this.registry.registerBrushType(VoltMeterBrush.class, "volt", "voltmeter");
		this.registry.registerBrushType(VoxelBrush.class, "v", "voxel");
		this.registry.registerBrushType(VoxelDiscBrush.class, "vd", "voxeldisc");
		this.registry.registerBrushType(VoxelDiscFaceBrush.class, "vdf", "voxeldiscface");
		this.registry.registerBrushType(WarpBrush.class, "world", "warp");
	}
}
