package com.thevoxelbox.voxelsniper;

import com.thevoxelbox.voxelsniper.brush.type.performer.BallBrush;
import com.thevoxelbox.voxelsniper.brush.type.BiomeBrush;
import com.thevoxelbox.voxelsniper.brush.type.blend.BlendBallBrush;
import com.thevoxelbox.voxelsniper.brush.type.blend.BlendDiscBrush;
import com.thevoxelbox.voxelsniper.brush.type.blend.BlendVoxelBrush;
import com.thevoxelbox.voxelsniper.brush.type.blend.BlendVoxelDiscBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.BlobBrush;
import com.thevoxelbox.voxelsniper.brush.type.BlockResetBrush;
import com.thevoxelbox.voxelsniper.brush.type.BlockResetSurfaceBrush;
import com.thevoxelbox.voxelsniper.brush.BrushRegistry;
import com.thevoxelbox.voxelsniper.brush.type.canyon.CanyonBrush;
import com.thevoxelbox.voxelsniper.brush.type.canyon.CanyonSelectionBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.CheckerVoxelDiscBrush;
import com.thevoxelbox.voxelsniper.brush.type.CleanSnowBrush;
import com.thevoxelbox.voxelsniper.brush.type.stamp.CloneStampBrush;
import com.thevoxelbox.voxelsniper.brush.type.CometBrush;
import com.thevoxelbox.voxelsniper.brush.type.CopyPastaBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.CylinderBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.DiscBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.DiscFaceBrush;
import com.thevoxelbox.voxelsniper.brush.type.DomeBrush;
import com.thevoxelbox.voxelsniper.brush.type.DrainBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.EllipseBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.EllipsoidBrush;
import com.thevoxelbox.voxelsniper.brush.type.EntityBrush;
import com.thevoxelbox.voxelsniper.brush.type.EntityRemovalBrush;
import com.thevoxelbox.voxelsniper.brush.type.EraserBrush;
import com.thevoxelbox.voxelsniper.brush.type.ErodeBrush;
import com.thevoxelbox.voxelsniper.brush.type.ExtrudeBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.FillDownBrush;
import com.thevoxelbox.voxelsniper.brush.type.FlatOceanBrush;
import com.thevoxelbox.voxelsniper.brush.type.GenerateTreeBrush;
import com.thevoxelbox.voxelsniper.brush.type.HeatRayBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.JaggedLineBrush;
import com.thevoxelbox.voxelsniper.brush.type.JockeyBrush;
import com.thevoxelbox.voxelsniper.brush.type.LightningBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.LineBrush;
import com.thevoxelbox.voxelsniper.brush.type.MoveBrush;
import com.thevoxelbox.voxelsniper.brush.type.OceanBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.OverlayBrush;
import com.thevoxelbox.voxelsniper.brush.type.PaintingBrush;
import com.thevoxelbox.voxelsniper.brush.type.PullBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.PunishBrush;
import com.thevoxelbox.voxelsniper.brush.type.RandomErodeBrush;
import com.thevoxelbox.voxelsniper.brush.type.RegenerateChunkBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.RingBrush;
import com.thevoxelbox.voxelsniper.brush.type.Rotation2DBrush;
import com.thevoxelbox.voxelsniper.brush.type.Rotation2DVerticalBrush;
import com.thevoxelbox.voxelsniper.brush.type.Rotation3DBrush;
import com.thevoxelbox.voxelsniper.brush.type.RulerBrush;
import com.thevoxelbox.voxelsniper.brush.type.ScannerBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.SetBrush;
import com.thevoxelbox.voxelsniper.brush.type.SetRedstoneFlipBrush;
import com.thevoxelbox.voxelsniper.brush.type.ShellBallBrush;
import com.thevoxelbox.voxelsniper.brush.type.ShellSetBrush;
import com.thevoxelbox.voxelsniper.brush.type.ShellVoxelBrush;
import com.thevoxelbox.voxelsniper.brush.type.SignOverwriteBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.SnipeBrush;
import com.thevoxelbox.voxelsniper.brush.type.SnowConeBrush;
import com.thevoxelbox.voxelsniper.brush.type.SpiralStaircaseBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.SplatterBallBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.SplatterDiscBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.SplatterOverlayBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.SplatterVoxelBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.SplineBrush;
import com.thevoxelbox.voxelsniper.brush.type.StencilBrush;
import com.thevoxelbox.voxelsniper.brush.type.StencilListBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.ThreePointCircleBrush;
import com.thevoxelbox.voxelsniper.brush.type.TreeSnipeBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.TriangleBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.UnderlayBrush;
import com.thevoxelbox.voxelsniper.brush.type.VoltMeterBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.VoxelBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.VoxelDiscBrush;
import com.thevoxelbox.voxelsniper.brush.type.performer.VoxelDiscFaceBrush;
import com.thevoxelbox.voxelsniper.brush.type.WarpBrush;

public class BrushRegistrar {

	private BrushRegistry registry;

	public BrushRegistrar(BrushRegistry registry) {
		this.registry = registry;
	}

	public void registerBrushes() {
		this.registry.registerBrush(BallBrush.class, "b", "ball");
		this.registry.registerBrush(BiomeBrush.class, "bio", "biome");
		this.registry.registerBrush(BlendBallBrush.class, "bb", "blendball");
		this.registry.registerBrush(BlendDiscBrush.class, "bd", "blenddisc");
		this.registry.registerBrush(BlendVoxelBrush.class, "bv", "blendvoxel");
		this.registry.registerBrush(BlendVoxelDiscBrush.class, "bvd", "blendvoxeldisc");
		this.registry.registerBrush(BlobBrush.class, "blob", "splatblob");
		this.registry.registerBrush(BlockResetBrush.class, "brb", "blockresetbrush");
		this.registry.registerBrush(BlockResetSurfaceBrush.class, "brbs", "blockresetbrushsurface");
		this.registry.registerBrush(CanyonBrush.class, "ca", "canyon");
		this.registry.registerBrush(CanyonSelectionBrush.class, "cas", "canyonselection");
		this.registry.registerBrush(CheckerVoxelDiscBrush.class, "cvd", "checkervoxeldisc");
		this.registry.registerBrush(CleanSnowBrush.class, "cls", "cleansnow");
		this.registry.registerBrush(CloneStampBrush.class, "cs", "clonestamp");
		this.registry.registerBrush(CometBrush.class, "com", "comet");
		this.registry.registerBrush(CopyPastaBrush.class, "cp", "copypasta");
		this.registry.registerBrush(CylinderBrush.class, "c", "cylinder");
		this.registry.registerBrush(DiscBrush.class, "d", "disc");
		this.registry.registerBrush(DiscFaceBrush.class, "df", "discface");
		this.registry.registerBrush(DomeBrush.class, "dome", "domebrush");
		this.registry.registerBrush(DrainBrush.class, "drain");
		this.registry.registerBrush(EllipseBrush.class, "el", "ellipse");
		this.registry.registerBrush(EllipsoidBrush.class, "elo", "ellipsoid");
		this.registry.registerBrush(EntityBrush.class, "en", "entity");
		this.registry.registerBrush(EntityRemovalBrush.class, "er", "entityremoval");
		this.registry.registerBrush(EraserBrush.class, "erase", "eraser");
		this.registry.registerBrush(ErodeBrush.class, "e", "erode");
		this.registry.registerBrush(ExtrudeBrush.class, "ex", "extrude");
		this.registry.registerBrush(FillDownBrush.class, "fd", "filldown");
		this.registry.registerBrush(FlatOceanBrush.class, "fo", "flatocean");
		this.registry.registerBrush(GenerateTreeBrush.class, "gt", "generatetree");
		this.registry.registerBrush(HeatRayBrush.class, "hr", "heatray");
		this.registry.registerBrush(JaggedLineBrush.class, "j", "jagged");
		this.registry.registerBrush(JockeyBrush.class, "jockey");
		this.registry.registerBrush(LightningBrush.class, "light", "lightning");
		this.registry.registerBrush(LineBrush.class, "l", "line");
		this.registry.registerBrush(MoveBrush.class, "mv", "move");
		this.registry.registerBrush(OceanBrush.class, "o", "ocean");
		this.registry.registerBrush(OverlayBrush.class, "over", "overlay");
		this.registry.registerBrush(PaintingBrush.class, "paint", "painting");
		this.registry.registerBrush(PullBrush.class, "pull");
		this.registry.registerBrush(PunishBrush.class, "p", "punish");
		this.registry.registerBrush(RandomErodeBrush.class, "re", "randomerode");
		this.registry.registerBrush(RegenerateChunkBrush.class, "gc", "generatechunk");
		this.registry.registerBrush(RingBrush.class, "ri", "ring");
		this.registry.registerBrush(Rotation2DBrush.class, "rot2", "rotation2d");
		this.registry.registerBrush(Rotation2DVerticalBrush.class, "rot2v", "rotation2dvertical");
		this.registry.registerBrush(Rotation3DBrush.class, "rot3", "rotation3d");
		this.registry.registerBrush(RulerBrush.class, "r", "ruler");
		this.registry.registerBrush(ScannerBrush.class, "sc", "scanner");
		this.registry.registerBrush(SetBrush.class, "set");
		this.registry.registerBrush(SetRedstoneFlipBrush.class, "setrf", "setredstoneflip");
		this.registry.registerBrush(ShellBallBrush.class, "shb", "shellball");
		this.registry.registerBrush(ShellSetBrush.class, "shs", "shellset");
		this.registry.registerBrush(ShellVoxelBrush.class, "shv", "shellvoxel");
		this.registry.registerBrush(SignOverwriteBrush.class, "sio", "signoverwriter");
		this.registry.registerBrush(SnipeBrush.class, "s", "snipe");
		this.registry.registerBrush(SnowConeBrush.class, "snow", "snowcone");
		this.registry.registerBrush(SpiralStaircaseBrush.class, "sstair", "spiralstaircase");
		this.registry.registerBrush(SplatterBallBrush.class, "sb", "splatball");
		this.registry.registerBrush(SplatterDiscBrush.class, "sd", "splatdisc");
		this.registry.registerBrush(SplatterOverlayBrush.class, "sover", "splatteroverlay");
		this.registry.registerBrush(SplatterVoxelBrush.class, "sv", "splattervoxel");
		this.registry.registerBrush(SplatterDiscBrush.class, "svd", "splatvoxeldisc");
		this.registry.registerBrush(SplineBrush.class, "sp", "spline");
		this.registry.registerBrush(StencilBrush.class, "st", "stencil");
		this.registry.registerBrush(StencilListBrush.class, "sl", "stencillist");
		this.registry.registerBrush(ThreePointCircleBrush.class, "tpc", "threepointcircle");
		this.registry.registerBrush(TreeSnipeBrush.class, "t", "tree", "treesnipe");
		this.registry.registerBrush(TriangleBrush.class, "tri", "triangle");
		this.registry.registerBrush(UnderlayBrush.class, "under", "underlay");
		this.registry.registerBrush(VoltMeterBrush.class, "volt", "voltmeter");
		this.registry.registerBrush(VoxelBrush.class, "v", "voxel");
		this.registry.registerBrush(VoxelDiscBrush.class, "vd", "voxeldisc");
		this.registry.registerBrush(VoxelDiscFaceBrush.class, "vdf", "voxeldiscface");
		this.registry.registerBrush(WarpBrush.class, "world", "warp");
	}
}
