package com.thevoxelbox.voxelsniper;

import com.thevoxelbox.voxelsniper.brush.BallBrush;
import com.thevoxelbox.voxelsniper.brush.BiomeBrush;
import com.thevoxelbox.voxelsniper.brush.BlendBallBrush;
import com.thevoxelbox.voxelsniper.brush.BlendDiscBrush;
import com.thevoxelbox.voxelsniper.brush.BlendVoxelBrush;
import com.thevoxelbox.voxelsniper.brush.BlendVoxelDiscBrush;
import com.thevoxelbox.voxelsniper.brush.BlobBrush;
import com.thevoxelbox.voxelsniper.brush.BlockResetBrush;
import com.thevoxelbox.voxelsniper.brush.BlockResetSurfaceBrush;
import com.thevoxelbox.voxelsniper.brush.CanyonBrush;
import com.thevoxelbox.voxelsniper.brush.CanyonSelectionBrush;
import com.thevoxelbox.voxelsniper.brush.CheckerVoxelDiscBrush;
import com.thevoxelbox.voxelsniper.brush.CleanSnowBrush;
import com.thevoxelbox.voxelsniper.brush.CloneStampBrush;
import com.thevoxelbox.voxelsniper.brush.CometBrush;
import com.thevoxelbox.voxelsniper.brush.CopyPastaBrush;
import com.thevoxelbox.voxelsniper.brush.CylinderBrush;
import com.thevoxelbox.voxelsniper.brush.DiscBrush;
import com.thevoxelbox.voxelsniper.brush.DiscFaceBrush;
import com.thevoxelbox.voxelsniper.brush.DomeBrush;
import com.thevoxelbox.voxelsniper.brush.DrainBrush;
import com.thevoxelbox.voxelsniper.brush.EllipseBrush;
import com.thevoxelbox.voxelsniper.brush.EllipsoidBrush;
import com.thevoxelbox.voxelsniper.brush.EntityBrush;
import com.thevoxelbox.voxelsniper.brush.EntityRemovalBrush;
import com.thevoxelbox.voxelsniper.brush.EraserBrush;
import com.thevoxelbox.voxelsniper.brush.ErodeBrush;
import com.thevoxelbox.voxelsniper.brush.ExtrudeBrush;
import com.thevoxelbox.voxelsniper.brush.FillDownBrush;
import com.thevoxelbox.voxelsniper.brush.FlatOceanBrush;
import com.thevoxelbox.voxelsniper.brush.GenerateTreeBrush;
import com.thevoxelbox.voxelsniper.brush.HeatRayBrush;
import com.thevoxelbox.voxelsniper.brush.JaggedLineBrush;
import com.thevoxelbox.voxelsniper.brush.JockeyBrush;
import com.thevoxelbox.voxelsniper.brush.LightningBrush;
import com.thevoxelbox.voxelsniper.brush.LineBrush;
import com.thevoxelbox.voxelsniper.brush.MoveBrush;
import com.thevoxelbox.voxelsniper.brush.OceanBrush;
import com.thevoxelbox.voxelsniper.brush.OverlayBrush;
import com.thevoxelbox.voxelsniper.brush.PaintingBrush;
import com.thevoxelbox.voxelsniper.brush.PullBrush;
import com.thevoxelbox.voxelsniper.brush.PunishBrush;
import com.thevoxelbox.voxelsniper.brush.RandomErodeBrush;
import com.thevoxelbox.voxelsniper.brush.RegenerateChunkBrush;
import com.thevoxelbox.voxelsniper.brush.RingBrush;
import com.thevoxelbox.voxelsniper.brush.Rot2DBrush;
import com.thevoxelbox.voxelsniper.brush.Rot2DvertBrush;
import com.thevoxelbox.voxelsniper.brush.Rot3DBrush;
import com.thevoxelbox.voxelsniper.brush.RulerBrush;
import com.thevoxelbox.voxelsniper.brush.ScannerBrush;
import com.thevoxelbox.voxelsniper.brush.SetBrush;
import com.thevoxelbox.voxelsniper.brush.SetRedstoneFlipBrush;
import com.thevoxelbox.voxelsniper.brush.ShellBallBrush;
import com.thevoxelbox.voxelsniper.brush.ShellSetBrush;
import com.thevoxelbox.voxelsniper.brush.ShellVoxelBrush;
import com.thevoxelbox.voxelsniper.brush.SignOverwriteBrush;
import com.thevoxelbox.voxelsniper.brush.SnipeBrush;
import com.thevoxelbox.voxelsniper.brush.SnowConeBrush;
import com.thevoxelbox.voxelsniper.brush.SpiralStaircaseBrush;
import com.thevoxelbox.voxelsniper.brush.SplatterBallBrush;
import com.thevoxelbox.voxelsniper.brush.SplatterDiscBrush;
import com.thevoxelbox.voxelsniper.brush.SplatterOverlayBrush;
import com.thevoxelbox.voxelsniper.brush.SplatterVoxelBrush;
import com.thevoxelbox.voxelsniper.brush.SplineBrush;
import com.thevoxelbox.voxelsniper.brush.StencilBrush;
import com.thevoxelbox.voxelsniper.brush.StencilListBrush;
import com.thevoxelbox.voxelsniper.brush.ThreePointCircleBrush;
import com.thevoxelbox.voxelsniper.brush.TreeSnipeBrush;
import com.thevoxelbox.voxelsniper.brush.TriangleBrush;
import com.thevoxelbox.voxelsniper.brush.UnderlayBrush;
import com.thevoxelbox.voxelsniper.brush.VoltMeterBrush;
import com.thevoxelbox.voxelsniper.brush.VoxelBrush;
import com.thevoxelbox.voxelsniper.brush.VoxelDiscBrush;
import com.thevoxelbox.voxelsniper.brush.VoxelDiscFaceBrush;
import com.thevoxelbox.voxelsniper.brush.WarpBrush;

public class BrushRegistrar {

	private BrushRegistry registry;

	public BrushRegistrar(BrushRegistry registry) {
		this.registry = registry;
	}

	public void registerBrushes() {
		this.registry.registerBrush(BallBrush.class, "b", "ball");
		this.registry.registerBrush(BiomeBrush.class, "bio", "biome");
		this.registry.registerBrush(BlendBallBrush.class, "bb", "blendball");
		this.registry.registerBrush(BlendDiscBrush.class, "bd", "blenddisc");
		this.registry.registerBrush(BlendVoxelBrush.class, "bv", "blendvoxel");
		this.registry.registerBrush(BlendVoxelDiscBrush.class, "bvd", "blendvoxeldisc");
		this.registry.registerBrush(BlobBrush.class, "blob", "splatblob");
		this.registry.registerBrush(BlockResetBrush.class, "brb", "blockresetbrush");
		this.registry.registerBrush(BlockResetSurfaceBrush.class, "brbs", "blockresetbrushsurface");
		this.registry.registerBrush(CanyonBrush.class, "ca", "canyon");
		this.registry.registerBrush(CanyonSelectionBrush.class, "cas", "canyonselection");
		this.registry.registerBrush(CheckerVoxelDiscBrush.class, "cvd", "checkervoxeldisc");
		this.registry.registerBrush(CleanSnowBrush.class, "cls", "cleansnow");
		this.registry.registerBrush(CloneStampBrush.class, "cs", "clonestamp");
		this.registry.registerBrush(CometBrush.class, "com", "comet");
		this.registry.registerBrush(CopyPastaBrush.class, "cp", "copypasta");
		this.registry.registerBrush(CylinderBrush.class, "c", "cylinder");
		this.registry.registerBrush(DiscBrush.class, "d", "disc");
		this.registry.registerBrush(DiscFaceBrush.class, "df", "discface");
		this.registry.registerBrush(DomeBrush.class, "dome", "domebrush");
		this.registry.registerBrush(DrainBrush.class, "drain");
		this.registry.registerBrush(EllipseBrush.class, "el", "ellipse");
		this.registry.registerBrush(EllipsoidBrush.class, "elo", "ellipsoid");
		this.registry.registerBrush(EntityBrush.class, "en", "entity");
		this.registry.registerBrush(EntityRemovalBrush.class, "er", "entityremoval");
		this.registry.registerBrush(EraserBrush.class, "erase", "eraser");
		this.registry.registerBrush(ErodeBrush.class, "e", "erode");
		this.registry.registerBrush(ExtrudeBrush.class, "ex", "extrude");
		this.registry.registerBrush(FillDownBrush.class, "fd", "filldown");
		this.registry.registerBrush(FlatOceanBrush.class, "fo", "flatocean");
		this.registry.registerBrush(GenerateTreeBrush.class, "gt", "generatetree");
		this.registry.registerBrush(HeatRayBrush.class, "hr", "heatray");
		this.registry.registerBrush(JaggedLineBrush.class, "j", "jagged");
		this.registry.registerBrush(JockeyBrush.class, "jockey");
		this.registry.registerBrush(LightningBrush.class, "light", "lightning");
		this.registry.registerBrush(LineBrush.class, "l", "line");
		this.registry.registerBrush(MoveBrush.class, "mv", "move");
		this.registry.registerBrush(OceanBrush.class, "o", "ocean");
		this.registry.registerBrush(OverlayBrush.class, "over", "overlay");
		this.registry.registerBrush(PaintingBrush.class, "paint", "painting");
		this.registry.registerBrush(PullBrush.class, "pull");
		this.registry.registerBrush(PunishBrush.class, "p", "punish");
		this.registry.registerBrush(RandomErodeBrush.class, "re", "randomerode");
		this.registry.registerBrush(RegenerateChunkBrush.class, "gc", "generatechunk");
		this.registry.registerBrush(RingBrush.class, "ri", "ring");
		this.registry.registerBrush(Rot2DBrush.class, "rot2", "rotation2d");
		this.registry.registerBrush(Rot2DvertBrush.class, "rot2v", "rotation2dvertical");
		this.registry.registerBrush(Rot3DBrush.class, "rot3", "rotation3d");
		this.registry.registerBrush(RulerBrush.class, "r", "ruler");
		this.registry.registerBrush(ScannerBrush.class, "sc", "scanner");
		this.registry.registerBrush(SetBrush.class, "set");
		this.registry.registerBrush(SetRedstoneFlipBrush.class, "setrf", "setredstoneflip");
		this.registry.registerBrush(ShellBallBrush.class, "shb", "shellball");
		this.registry.registerBrush(ShellSetBrush.class, "shs", "shellset");
		this.registry.registerBrush(ShellVoxelBrush.class, "shv", "shellvoxel");
		this.registry.registerBrush(SignOverwriteBrush.class, "sio", "signoverwriter");
		this.registry.registerBrush(SnipeBrush.class, "s", "snipe");
		this.registry.registerBrush(SnowConeBrush.class, "snow", "snowcone");
		this.registry.registerBrush(SpiralStaircaseBrush.class, "sstair", "spiralstaircase");
		this.registry.registerBrush(SplatterBallBrush.class, "sb", "splatball");
		this.registry.registerBrush(SplatterDiscBrush.class, "sd", "splatdisc");
		this.registry.registerBrush(SplatterOverlayBrush.class, "sover", "splatteroverlay");
		this.registry.registerBrush(SplatterVoxelBrush.class, "sv", "splattervoxel");
		this.registry.registerBrush(SplatterDiscBrush.class, "svd", "splatvoxeldisc");
		this.registry.registerBrush(SplineBrush.class, "sp", "spline");
		this.registry.registerBrush(StencilBrush.class, "st", "stencil");
		this.registry.registerBrush(StencilListBrush.class, "sl", "stencillist");
		this.registry.registerBrush(ThreePointCircleBrush.class, "tpc", "threepointcircle");
		this.registry.registerBrush(TreeSnipeBrush.class, "t", "tree", "treesnipe");
		this.registry.registerBrush(TriangleBrush.class, "tri", "triangle");
		this.registry.registerBrush(UnderlayBrush.class, "under", "underlay");
		this.registry.registerBrush(VoltMeterBrush.class, "volt", "voltmeter");
		this.registry.registerBrush(VoxelBrush.class, "v", "voxel");
		this.registry.registerBrush(VoxelDiscBrush.class, "vd", "voxeldisc");
		this.registry.registerBrush(VoxelDiscFaceBrush.class, "vdf", "voxeldiscface");
		this.registry.registerBrush(WarpBrush.class, "world", "warp");
	}
}
